description = "Examples for the LVGL embedded GUI framework Ada binding"
name = "lvgl_ada_examples"
version = "1.0.0-dev"
executables = ["lvgl_ada_examples"]
licenses = "MIT"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/lvgl-ada-examples"
tags = ["gui", "lvgl"]

project-files = ["lvgl_ada_examples.gpr"]

[[depends-on]]
lvgl_ada = "^1"
lvgl_ada_simulator = "^1"

# Dev pins
[[pins]]
lvgl_ada = { url = "https://github.com/Fabien-Chouteau/lvgl-ada" }
lvgl_ada_simulator = { url = "https://github.com/Fabien-Chouteau/lvgl-ada-simulator" }

[configuration.values]
lvgl_ada.Pixel_Bit_Depth = "Pix_32bit"
lvgl_ada.Horizontal_Resolution = 800
lvgl_ada.Vertical_Resolution = 480
lvgl_ada.Density_Per_Inch = 100
lvgl_ada.Theme_Live_Update = true
lvgl_ada.Default_font = "dejavu_20"
# lvgl_ada.Log_Level = "Trace"
# lvgl_ada.Log_With_Printf = true
