description = "Examples for the LVGL embedded GUI framework Ada binding"
name = "lvgl_ada_examples"
version = "0.2.0-dev"
executables = ["lvgl_ada_examples"]
licenses = "MIT"
maintainers = ["fabien.chouteau@gmail.com"]
maintainers-logins = ["Fabien-Chouteau"]
project-files = ["lvgl_ada_examples.gpr"]
tags = ["gui", "lvgl"]

[[depends-on]]
lvgl_ada = "~0.2.0"
lvgl_ada_simulator = "~0.2.0"

[configuration.values]
lvgl_ada.Pixel_Bit_Depth = "Pix_32bit"
lvgl_ada.Horizontal_Resolution = 800
lvgl_ada.Vertical_Resolution = 480
lvgl_ada.Density_Per_Inch = 100
lvgl_ada.Theme_Live_Update = true
lvgl_ada.Default_font = "dejavu_20"
