on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  build_native:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: alire-project/setup-alire@v1
        with:
          toolchain: gnat_native gprbuild --disable-assistant

      - run: alr build

        # Produce an Alire release manifest
      - name: Make Release Manifest
        if: (startsWith(matrix.os, 'ubuntu'))
        run: |
          # Set user GitHub login required for `alr publish`
          alr config --set --global user.github_login ${{github.repository_owner}}

          # Run Alire publish assistant
          alr -vv -d publish ${{github.server_url}}/${{github.repository}} ${{github.sha}}

          # If this is a release build, upload the manifest to the release
          if ["${{github.event_name}}" = "release" ]; then
            gh release upload "${{github.ref}}" "$(ls alire/releases/*.toml | head -n 1)"
          fi
